export const DOUBLE_BACK_EXIT_DELAY = 2000
export const NOTIFICATION_TIMEOUT = 3000
export const MIN_OFFLINE_RETRY_DELAY = 1000
export const MAX_OFFLINE_RETRY_DELAY = 10000
export const PERMISSION_REQUEST_TIMEOUT = 30000
